[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = '''
let g:startify_bookmarks = [ {'53': '~/workspace/freemarket_sample_53b'}, {'d': '~/workspace/dotfiles'}]
let g:startify_change_to_dir = 1
let g:startify_change_to_vcs_root = 1
let g:ascii = [
    \ '■■     ■■■  ■■■■■■■■     ■■■■   ■■■■   ■■■  ■■■■  ■■■      ■■■',
    \ ' ■■     ■    ■■    ■   ■■   ■■    ■     ■    ■■    ■■      ■■ ',
    \ ' ■■■    ■    ■■    ■   ■     ■■   ■     ■    ■■    ■■      ■■ ',
    \ ' ■ ■    ■    ■■       ■■      ■   ■■   ■     ■■    ■■■    ■ ■ ',
    \ ' ■  ■   ■    ■■  ■    ■       ■    ■   ■     ■■    ■ ■    ■ ■ ',
    \ ' ■  ■■  ■    ■■■■■    ■       ■    ■   ■     ■■    ■ ■■     ■ ',
    \ ' ■   ■■ ■    ■■  ■    ■       ■    ■■ ■      ■■    ■  ■  ■  ■ ',
    \ ' ■    ■ ■    ■■       ■■      ■     ■ ■      ■■    ■  ■  ■  ■ ',
    \ ' ■    ■■■    ■■    ■   ■     ■■     ■■■      ■■    ■  ■■■   ■ ',
    \ ' ■     ■■    ■■    ■   ■■    ■       ■       ■■    ■   ■■   ■ ',
    \ '■■■     ■   ■■■■■■■■     ■■■■        ■      ■■■■  ■■■  ■   ■■■',
    \ ]
let g:startify_custom_header = g:ascii
let g:startify_enable_special = 1   
let g:startify_lists = [
          \ { 'type': 'files',     'header': ['〇 最近使ったファイル'] },
          \ { 'type': 'sessions',  'header': ['   Sessions'] },
          \ { 'type': 'bookmarks', 'header': ['〇 Bookmarks'] }
          \ ]
let g:startify_skiplist = [
        \ '^/tmp',
        \ '.swap$',
        \ '.tmp$',
        \ ]
let g:startify_update_oldfiles = 1

" For Misc options
let g:startify_commands = []
let g:startify_custom_footer = ['-------------------------------------------------------']
let g:startify_disable_at_vimenter = 0
let g:startify_enable_unsafe = 0
let g:startify_files_number = 5
let g:startify_fortune_use_unicode = 0
let g:startify_padding_left = 4
let g:startify_relative_path = 1
let g:startify_use_env = 1

" For Sessions     
let g:startify_session_autoload = 1     
let g:startify_session_before_save = ['echo "Saving this session ..."']    
let g:startify_session_delete_buffers = 0     
let g:startify_session_dir = '~/.vim/session'     
let g:startify_session_number = 20     
let g:startify_session_persistence = 1     
let g:startify_session_remove_lines = ['setlocal', 'winheight']    
let g:startify_session_savecmds = ['echo "Saved a session."']
let g:startify_session_savevars = [    
           \ 'g:startify_session_savevars',    
           \ 'g:startify_session_savecmds',    
           \ ]    
let g:startify_session_sort = 1
'''
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
map <C-e> :NERDTreeToggle<CR>
let NERDTreeShowHidden=1
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
let NERDTreeShowBookmarks=1
let NERDTreeTreeWinSize=27
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  let g:winresizer_start_key = '<C-r>'
'''

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup   = 1
'''

#[[plugins]]
#repo = 'Shougo/deoppet.nvim'
# hook_add = '''
#call deoppet#initialize()
#call deoppet#custom#option('snippets_dirs', globpath(&runtimepath, 'neosnippets', 1, 1))
#'''

#[[plugins]]
#repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = './install.sh'

[[plugins]]
repo = 'Shougo/deoplete-nextword'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_color_term = 239
let g:indentLine_char = '┊'
let g:indentLine_leadingSpaceChar = '·'
'''

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
nmap <silent> ,f :<C-u>Denite file<CR>
nmap <silent> ,r :<C-u>Denite file/rec<CR>
nmap <silent> ,g :<C-u>Denite grep<CR>
nmap <silent> ,t :<C-u>Denite file/type<CR>
nmap <silent> ,b :<C-u>Denite buffer<CR>
nmap <silent> ,l :<C-u>Denite line<CR>
" Define mappings
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
  \ denite#do_map('toggle_select').'j'
endfunction
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('file/rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])

'''

